'use client';

/**
 * A tab's summary, generated by the on-device (WebGPU) engine instead of the
 * server chain.
 *
 * It reuses `browserChatEvents` wholesale rather than talking to the engine
 * directly: that path already fetches the data snapshot from /api/ai/context,
 * loads (or downloads) the model, reports progress, and strips a thinking
 * block. The only thing that differs here is the message — one instruction
 * asking for the same JSON the server's summaries return — so both paths land
 * in the same `{ summary, recommendations }` shape and the cards render one way.
 *
 * ⚠️ Never call this on a timer. A server summary is a cached HTTP request; this
 * one can spend a minute of somebody's GPU (and, on a cold cache, a
 * multi-gigabyte download) — so it runs when the user presses Analyze, and at
 * no other time.
 */

import { MSG, fill } from '@/config/messages.th';
import { browserChatEvents } from '@/lib/ai/browser/chat';

/**
 * Strip fences and pull the JSON object out — the browser models are small and
 * fence their output far more often than a hosted one, even when told not to.
 */
function parseLoose(text) {
  const cleaned = text
    .replace(/^```(?:json)?\s*/i, '')
    .replace(/```\s*$/, '')
    .trim();
  const start = cleaned.indexOf('{');
  const end = cleaned.lastIndexOf('}');
  if (start < 0 || end <= start) return null;
  try {
    return JSON.parse(cleaned.slice(start, end + 1));
  } catch {
    return null;
  }
}

/**
 * Shape whatever the model produced into the card's contract.
 *
 * A 2B model asked for JSON will sometimes answer in prose regardless, and that
 * prose is usually a perfectly good summary — throwing it away for failing a
 * format it was never able to honour would be the wrong kind of strict. So a
 * parse failure demotes to "the whole reply is the summary" instead of an error.
 */
function toSummary(text, model) {
  const parsed = parseLoose(text);
  const maxRecs = MSG.analyze.maxRecs;

  const recommendations = Array.isArray(parsed?.recommendations)
    ? parsed.recommendations
        .filter((r) => r && typeof r.text === 'string')
        .slice(0, maxRecs)
        .map((r) => ({ level: r.level || 'info', text: r.text }))
    : [];

  const summary =
    typeof parsed?.summary === 'string' && parsed.summary.trim()
      ? parsed.summary.trim()
      : text.trim();

  return {
    ok: true,
    summary,
    recommendations,
    provider: 'browser',
    model,
    generatedAt: Date.now(),
  };
}

/**
 * Run one scope's summary on this machine. Resolves to the same payload shape
 * GET /api/ai/summary returns, so a card cannot tell which engine wrote it.
 *
 * `onStatus` receives the engine's own progress lines (downloading, preparing,
 * chewing through the prompt) — on a cold model those cover minutes during
 * which nothing else would move.
 */
export async function runBrowserSummary({
  scope,
  apiBase = '',
  deviceId,
  lang = 'th',
  modelId,
  labels,
  onStatus,
  signal,
}) {
  const instruction = MSG.scopes[scope] ?? MSG.scopes.environment;
  const prompt = `${instruction}\n\n${fill(MSG.scopes.jsonShape, { maxRecs: MSG.analyze.maxRecs })}`;

  let text = '';
  let model = modelId;

  for await (const ev of browserChatEvents({
    messages: [{ role: 'user', content: prompt }],
    apiBase,
    deviceId,
    lang,
    modelId,
    // Thinking off: the answer is a fixed-shape JSON object, and the tokens a
    // reasoning pass would spend come out of the same budget as the answer.
    thinking: false,
    // The whole point of this path — the snapshot *is* the thing being summarised.
    sendContext: true,
    labels,
    signal,
  })) {
    if (ev.type === 'start' && ev.model) model = ev.model;
    else if (ev.type === 'status') onStatus?.(ev.text);
    else if (ev.type === 'delta') text += ev.text;
  }

  if (!text.trim()) throw new Error(MSG.scopes.noData);
  return toSummary(text, model);
}
